<?php

return array(
    array(
        'id'=>1,
        'title'=>'test1',
        'trade'=>array(
            array(
                'id'=>1,
                'title'=>'电子商务'
            ),
            array(
                'id'=>2,
                'title'=>'教育培训'
            ),
            array(
                'id'=>3,
                'title'=>'生物技术'
            ),
            array(
                'id'=>4,
                'title'=>'通讯数码'
            )
        )
    ),
    array(
    'id'=>2,
    'title'=>'test2',
    'trade'=>array(
            array(
                'id'=>5,
                'title'=>'烟草'
            ),
            array(
                'id'=>6,
                'title'=>'铁路'
            ),
            array(
                'id'=>7,
                'title'=>'建筑'
            ),
            array(
                'id'=>8,
                'title'=>'银行'
            )
        )
    )
);
